version: '3.8'

services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main-db
    ports:
      - "7432:5432"
    volumes:
      - main_db_volume:/var/lib/postgresql/data

volumes:
  main_db_volume:
    name: main_db_volume
